### ISSUE TITLE
error on start

### ISSUE THREAD

**Issue by pokecosimo** [GHYAKIMA/emptyserverstopper-mod#5]
[main/ERROR] [ne.mi.fm.lo.LanguageLoadingProvider/LOADING]: Missing language javafml version [41,) wanted by emptyserverstopper-forge-0.0.2.jar, found 40

**Comment by RealmKebab** [comment]
you're using another version of minecraft,
you're using 1.18.2 but the current version of this mod requires 1.19
![image](https://github.com/GHYAKIMA/emptyserverstopper-mod/assets/73048123/eb44ccac-5b87-4ba9-8e85-35742fa3b0fb)
![image](https://github.com/GHYAKIMA/emptyserverstopper-mod/assets/73048123/2d3e2877-a187-4901-9405-0a286dfc92fe)
